document.addEventListener("DOMContentLoaded", function () {
    new TypeIt("#hi", { 
        lifeLike: false, 
        speed: 0 
    })
      .type("S")
      .pause(336)
      .type("i")
      .pause(176)
      .type("z")
      .pause(347)
      .type("n")
      .pause(165)
      .type("i")
      .pause(187)
      .type("n")
      .pause(259)
      .type("g")
      .pause(398)
      .type(" ")
      .pause(1387)
      .type("s")
      .pause(141)
      .type("a")
      .pause(146)
      .type("y")
      .pause(320)
      .type("t")
      .pause(243)
      .type("i")
      .pause(331)
      .type("n")
      .pause(287)
      .type("g")
      .pause(150)
      .type("i")
      .pause(430)
      .type("z")
      .pause(714)
      .type("g")
      .pause(266)
      .type("a")
      .pause(205)
      .type(" ")
      .pause(861)
      .type("s")
      .pause(140)
      .type("a")
      .pause(298)
      .type("y")
      .pause(249)
      .type("t")
      .pause(762)
      .type(" ")
      .pause(924)
      .type("k")
      .pause(102)
      .type("e")
      .pause(174)
      .type("r")
      .pause(249)
      .type("a")
      .pause(210)
      .type("k")
      .pause(199)
      .type("m")
      .pause(115)
      .type("i")
      .pause(631)
      .type("?")
      .pause(246)
      .break()
      .go();
  });